name: Share Data Between Jobs

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate data in job1
        run: echo "Some data" > $GITHUB_WORKSPACE/data.txt

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Access data in job2
        run: cat $GITHUB_WORKSPACE/data.txt
